#!/usr/bin/env bash

set -e

source "$PWD/scripts/functions.sh"

sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

info 'updating dotfiles repository'
git pull --quiet;
success 'updated dotfiles repository'

if [[ ! $(which brew) ]]; then
  info 'installing homebrew'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  success 'installed homebrew'
fi

info 'updating homebrew installation'
/usr/local/bin/brew update
success 'updated homebrew installation'

info 'upgrading homebrew packages'
/usr/local/bin/brew upgrade
success 'upgraded homebrew packages'

info 'backing up application settings'
/usr/local/bin/mackup --force backup
success 'backed up application settings'

info 'updating Brewfile'
/usr/local/bin/brew bundle --force dump
success 'updated Brewfile'
