tap "homebrew/bundle"

brew "ack"
brew "openssl@1.1"
brew "gettext"
brew "awscli"
brew "binutils"
brew "bzip2"
brew "cmake"
brew "coreutils"
brew "curl"
brew "docker-completion"
brew "docker-compose"
brew "findutils"
brew "freetds"
brew "gh"
brew "git"
brew "go"
brew "openjdk"
brew "gradle"
brew "gzip"
brew "inetutils"
brew "make"
brew "mas"
brew "moreutils"
brew "node"
brew "pandoc"
brew "pyenv"
brew "rsync"
brew "spaceship"
brew "stow"
brew "wget"
brew "zlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

cask "google-cloud-sdk"

mas "Amphetamine", id: 937984704
mas "Boop", id: 1518425043
mas "Keynote", id: 409183694
mas "LittleIpsum", id: 405772121
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
